// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostAppCreateData, PostAppCreateError, PostAppCreateResponse, DeleteAppGetError, DeleteAppGetResponse, PutAppPutData, PutAppPutError, PutAppPutResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create a new application
 */
export const postAppCreate = <ThrowOnError extends boolean = false>(options?: Options<PostAppCreateData, ThrowOnError>) => { return (options?.client ?? client).post<PostAppCreateResponse, PostAppCreateError, ThrowOnError>({
    ...options,
    url: ''
}); };

/**
 * Create a new application
 */
export const deleteAppGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteAppGetResponse, DeleteAppGetError, ThrowOnError>({
    ...options,
    url: '/{id}'
}); };

/**
 * Create a new application
 */
export const putAppPut = <ThrowOnError extends boolean = false>(options?: Options<PutAppPutData, ThrowOnError>) => { return (options?.client ?? client).put<PutAppPutResponse, PutAppPutError, ThrowOnError>({
    ...options,
    url: '/{id}'
}); };