// This file is auto-generated by @hey-api/openapi-ts

export type PostAppCreateData = {
    body?: {
        name?: string;
        feature?: string;
    };
};

export type PostAppCreateResponse = ({
    name: string;
    env: string;
    day_offset: number;
    audiences: Array<{
        name: string;
        key: string;
        values: Array<(string)>;
    }>;
    query_params?: Array<{
        name: string;
    }>;
    features: Array<{
        name: string;
        kill: boolean;
        rule: (string | boolean | number);
    }>;
    theme: 'tomato' | 'red' | 'ruby' | 'crimson' | 'pink' | 'plum' | 'purple' | 'violet' | 'iris' | 'indigo' | 'blue' | 'cyan' | 'teal' | 'jade' | 'green' | 'grass' | 'bronze' | 'gold' | 'brown' | 'orange' | 'amber' | 'yellow' | 'lime' | 'mint' | 'sky';
});

export type PostAppCreateError = unknown;

export type DeleteAppGetResponse = ({
    name: string;
    env: string;
    day_offset: number;
    audiences: Array<{
        name: string;
        key: string;
        values: Array<(string)>;
    }>;
    query_params?: Array<{
        name: string;
    }>;
    features: Array<{
        name: string;
        kill: boolean;
        rule: (string | boolean | number);
    }>;
    theme: 'tomato' | 'red' | 'ruby' | 'crimson' | 'pink' | 'plum' | 'purple' | 'violet' | 'iris' | 'indigo' | 'blue' | 'cyan' | 'teal' | 'jade' | 'green' | 'grass' | 'bronze' | 'gold' | 'brown' | 'orange' | 'amber' | 'yellow' | 'lime' | 'mint' | 'sky';
});

export type DeleteAppGetError = unknown;

export type PutAppPutData = {
    body?: {
        name: string;
        env: string;
        day_offset: number;
        audiences: Array<{
            name: string;
            key: string;
            values: Array<(string)>;
        }>;
        query_params?: Array<{
            name: string;
        }>;
        features: Array<{
            name: string;
            kill: boolean;
            rule: (string | boolean | number);
        }>;
        theme: 'tomato' | 'red' | 'ruby' | 'crimson' | 'pink' | 'plum' | 'purple' | 'violet' | 'iris' | 'indigo' | 'blue' | 'cyan' | 'teal' | 'jade' | 'green' | 'grass' | 'bronze' | 'gold' | 'brown' | 'orange' | 'amber' | 'yellow' | 'lime' | 'mint' | 'sky';
    };
};

export type PutAppPutResponse = ({
    name: string;
    env: string;
    day_offset: number;
    audiences: Array<{
        name: string;
        key: string;
        values: Array<(string)>;
    }>;
    query_params?: Array<{
        name: string;
    }>;
    features: Array<{
        name: string;
        kill: boolean;
        rule: (string | boolean | number);
    }>;
    theme: 'tomato' | 'red' | 'ruby' | 'crimson' | 'pink' | 'plum' | 'purple' | 'violet' | 'iris' | 'indigo' | 'blue' | 'cyan' | 'teal' | 'jade' | 'green' | 'grass' | 'bronze' | 'gold' | 'brown' | 'orange' | 'amber' | 'yellow' | 'lime' | 'mint' | 'sky';
});

export type PutAppPutError = unknown;