// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file keat/core/v1/core.proto (package keat.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthRequest, AuthResponse, CreateAppRequest, CreateAppResponse, DeleteAppRequest, DeleteAppResponse, GetAppRequest, GetAppResponse, RemoveCohortRequest, RemoveCohortResponse, RemoveFeatureRequest, RemoveFeatureResponse, TargetRequest, TargetResponse, ToggleRequest, ToggleResponse } from "./core_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service keat.core.v1.KeatService
 */
export const KeatService = {
  typeName: "keat.core.v1.KeatService",
  methods: {
    /**
     * @generated from rpc keat.core.v1.KeatService.Auth
     */
    auth: {
      name: "Auth",
      I: AuthRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.GetApp
     */
    getApp: {
      name: "GetApp",
      I: GetAppRequest,
      O: GetAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.CreateApp
     */
    createApp: {
      name: "CreateApp",
      I: CreateAppRequest,
      O: CreateAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.DeleteApp
     */
    deleteApp: {
      name: "DeleteApp",
      I: DeleteAppRequest,
      O: DeleteAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.Toggle
     */
    toggle: {
      name: "Toggle",
      I: ToggleRequest,
      O: ToggleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.RemoveFeature
     */
    removeFeature: {
      name: "RemoveFeature",
      I: RemoveFeatureRequest,
      O: RemoveFeatureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.Target
     */
    target: {
      name: "Target",
      I: TargetRequest,
      O: TargetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.RemoveCohort
     */
    removeCohort: {
      name: "RemoveCohort",
      I: RemoveCohortRequest,
      O: RemoveCohortResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

