// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file keat/core/v1/core.proto (package keat.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAppRequest, CreateAppResponse, GetAppRequest, GetAppResponse, ToggleRequest, ToggleResponse, UpdateAppRequest, UpdateAppResponse, UpsertAudienceRequest, UpsertAudienceResponse } from "./core_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service keat.core.v1.KeatService
 */
export const KeatService = {
  typeName: "keat.core.v1.KeatService",
  methods: {
    /**
     * @generated from rpc keat.core.v1.KeatService.GetApp
     */
    getApp: {
      name: "GetApp",
      I: GetAppRequest,
      O: GetAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.CreateApp
     */
    createApp: {
      name: "CreateApp",
      I: CreateAppRequest,
      O: CreateAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.UpdateApp
     */
    updateApp: {
      name: "UpdateApp",
      I: UpdateAppRequest,
      O: UpdateAppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.UpsertAudience
     */
    upsertAudience: {
      name: "UpsertAudience",
      I: UpsertAudienceRequest,
      O: UpsertAudienceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc keat.core.v1.KeatService.Toggle
     */
    toggle: {
      name: "Toggle",
      I: ToggleRequest,
      O: ToggleResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

